LangString addOrReinstall ${LANG_FARSI} "افزودن/نصب دوبارهٔ اجزا"
LangString alreadyInstalled ${LANG_FARSI} "از قبل نصب شده"
LangString alreadyInstalledLong ${LANG_FARSI} "${PRODUCTNAME} ${VERSION} از قبل نصب شده است. کاری را که می‌خواهید انجام دهید انتخاب کنید و برای ادامه روی «بعدی» بزنید."
LangString appRunning ${LANG_FARSI} "{{product_name}} در حال اجراست! لطفاً اول آن را ببندید و دوباره تلاش کنید."
LangString appRunningOkKill ${LANG_FARSI} "{{product_name}} در حال اجراست!$\nبرای بستن آن روی «تأیید» بزنید"
LangString chooseMaintenanceOption ${LANG_FARSI} "گزینهٔ نگهداری را انتخاب کنید."
LangString choowHowToInstall ${LANG_FARSI} "انتخاب کنید ${PRODUCTNAME} چگونه نصب شود."
LangString createDesktop ${LANG_FARSI} "ساخت میان‌بر روی میز کار"
LangString dontUninstall ${LANG_FARSI} "حذف نکن"
LangString dontUninstallDowngrade ${LANG_FARSI} "حذف نکن (نصب نسخهٔ قدیمی‌تر بدون حذف در این نصب‌کننده غیرفعال است)"
LangString failedToKillApp ${LANG_FARSI} "بستن {{product_name}} ممکن نشد. لطفاً اول آن را ببندید و دوباره تلاش کنید"
LangString installingWebview2 ${LANG_FARSI} "در حال نصب WebView2..."
LangString newerVersionInstalled ${LANG_FARSI} "نسخهٔ جدیدتری از ${PRODUCTNAME} از قبل نصب شده است! نصب نسخهٔ قدیمی‌تر توصیه نمی‌شود. اگر واقعاً می‌خواهید این نسخهٔ قدیمی‌تر را نصب کنید، بهتر است اول نسخهٔ فعلی را حذف کنید. کاری را که می‌خواهید انجام دهید انتخاب کنید و برای ادامه روی «بعدی» بزنید."
LangString older ${LANG_FARSI} "قدیمی‌تر"
LangString olderOrUnknownVersionInstalled ${LANG_FARSI} "یک نسخهٔ $R4 از ${PRODUCTNAME} روی سیستم شما نصب است. توصیه می‌شود پیش از نصب، نسخهٔ فعلی را حذف کنید. کاری را که می‌خواهید انجام دهید انتخاب کنید و برای ادامه روی «بعدی» بزنید."
LangString silentDowngrades ${LANG_FARSI} "نصب نسخهٔ قدیمی‌تر در این نصب‌کننده غیرفعال است؛ نصب بی‌صدا ادامه نمی‌یابد، لطفاً از نصب‌کنندهٔ گرافیکی استفاده کنید.$\n"
LangString unableToUninstall ${LANG_FARSI} "حذف ممکن نشد!"
LangString uninstallApp ${LANG_FARSI} "حذف ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_FARSI} "حذف پیش از نصب"
LangString unknown ${LANG_FARSI} "ناشناخته"
LangString webview2AbortError ${LANG_FARSI} "نصب WebView2 ممکن نشد! برنامه بدون آن اجرا نمی‌شود. نصب‌کننده را دوباره اجرا کنید."
LangString webview2DownloadError ${LANG_FARSI} "خطا: دانلود WebView2 ممکن نشد - $0"
LangString webview2DownloadSuccess ${LANG_FARSI} "راه‌انداز WebView2 با موفقیت دانلود شد"
LangString webview2Downloading ${LANG_FARSI} "در حال دانلود راه‌انداز WebView2..."
LangString webview2InstallError ${LANG_FARSI} "خطا: نصب WebView2 با کد خروج $1 ناموفق بود"
LangString webview2InstallSuccess ${LANG_FARSI} "WebView2 با موفقیت نصب شد"
LangString deleteAppData ${LANG_FARSI} "حذف داده‌های برنامه"
